name: Deploy application
on:
  push:
    branches:
    - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Restart docker containers
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ./hackathon-backend
            git pull origin main
            docker-compose down
            docker-compose up -d --build
